
//! Autogenerated weights for `pallet_xqvm`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-04-07, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `KONRAD-DESKTOP`, CPU: `AMD Ryzen 9 7950X 16-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// /home/konrad/Projects/quip-protocol-rs/target/release/quip-network-node
// benchmark
// pallet
// --pallet
// pallet_xqvm
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// /home/konrad/Projects/quip-protocol-rs/pallets/xqvm/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_xqvm`.
pub trait WeightInfo {
	fn store_program(s: u32) -> Weight;
	fn execute_base() -> Weight;
}

/// Weights for `pallet_xqvm` using the Substrate node and target hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for SubstrateWeight<T> {
	/// Storage: `Xqvm::Programs` (r:1 w:1)
	/// Proof: `Xqvm::Programs` (`max_values`: None, `max_size`: Some(65572), added: 68047, mode: `MaxEncodedLen`)
	/// Storage: `Xqvm::ProgramOwner` (r:0 w:1)
	/// Proof: `Xqvm::ProgramOwner` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[3, 65536]`.
	fn store_program(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `69037`
		// Minimum execution time: 8_450_000 picoseconds.
		Weight::from_parts(8_655_105, 0)
			.saturating_add(Weight::from_parts(0, 69037))
			// Standard Error: 4
			.saturating_add(Weight::from_parts(1_061, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Xqvm::Programs` (r:1 w:0)
	/// Proof: `Xqvm::Programs` (`max_values`: None, `max_size`: Some(65572), added: 68047, mode: `MaxEncodedLen`)
	fn execute_base() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `66`
		//  Estimated: `69037`
		// Minimum execution time: 8_431_000 picoseconds.
		Weight::from_parts(9_015_000, 0)
			.saturating_add(Weight::from_parts(0, 69037))
			.saturating_add(T::DbWeight::get().reads(1))
	}
}

impl WeightInfo for () {
	fn store_program(s: u32) -> Weight {
		Weight::from_parts(8_655_105, 0)
			.saturating_add(Weight::from_parts(0, 69037))
			.saturating_add(Weight::from_parts(1_061, 0).saturating_mul(s.into()))
			.saturating_add(frame_support::weights::constants::RocksDbWeight::get().reads(1))
			.saturating_add(frame_support::weights::constants::RocksDbWeight::get().writes(2))
	}

	fn execute_base() -> Weight {
		Weight::from_parts(9_015_000, 0)
			.saturating_add(Weight::from_parts(0, 69037))
			.saturating_add(frame_support::weights::constants::RocksDbWeight::get().reads(1))
	}
}
